/**
 * Auto-generates a README.md for the AI-Ready Kit export.
 * Pure function — no side effects, no dependencies.
 */

const DOC_PURPOSE: Record<string, string> = {
  PRD: "Product requirements, user stories, and success metrics",
  "Design Document": "System design decisions and trade-offs",
  "Tech Stack": "Framework, library, database, and hosting choices",
  Architecture: "C4 model system architecture and component diagram",
  "Tech Spec": "Implementation blueprint with data models and business rules",
  Roadmap: "Phased milestones, timelines, and delivery plan",
  "API Spec": "Endpoint definitions, schemas, and authentication",
  "UI Design": "Design system, typography, color palette, and layouts",
  "Task List": "Nested implementation tasks with priorities",
  "Vibe Prompt": "AI-ready handoff prompt synthesizing all documents",
};

const DOC_FILENAME: Record<string, string> = {
  PRD: "prd.md",
  "Design Document": "design-document.md",
  "Tech Stack": "tech-stack.md",
  Architecture: "architecture.md",
  "Tech Spec": "tech-spec.md",
  Roadmap: "roadmap.md",
  "API Spec": "api-spec.md",
  "UI Design": "ui-design.md",
  "Task List": "task-list.md",
  "Vibe Prompt": "vibe-prompt.md",
};

export function getDocFilename(docType: string): string {
  return DOC_FILENAME[docType] ?? `${docType.toLowerCase().replace(/\s+/g, "-")}.md`;
}

export function generateReadme(
  documents: Record<string, string>,
  sessionName: string,
): string {
  const date = new Date().toISOString().split("T")[0];
  const docTypes = Object.keys(documents);
  const hasVibe = "Vibe Prompt" in documents;

  const docTable = docTypes
    .map((dt) => {
      const filename = getDocFilename(dt);
      const purpose = DOC_PURPOSE[dt] ?? "Project documentation";
      const location = dt === "Vibe Prompt" ? "`VIBE_PROMPT.md` (root)" : `\`docs/${filename}\``;
      return `| ${dt} | ${location} | ${purpose} |`;
    })
    .join("\n");

  return `# ${sessionName} — AI-Ready Project Kit

> Generated by APEX-CYBERNETIC · ${date}

## 📋 What Is This?

This kit contains all planning and specification documents for **${sessionName}**.
It is designed to be handed to any AI coding assistant to start development immediately.

## 🚀 Quick Start

${
  hasVibe
    ? `1. Open \`VIBE_PROMPT.md\` — this is your master instruction file
2. Give it to your AI assistant (Cursor, Claude, Copilot, Windsurf, etc.)
3. The AI will read all referenced docs from the \`docs/\` folder
4. Development begins immediately`
    : `1. Open the \`docs/\` folder and review each document
2. Start with the PRD to understand the project
3. Follow the Roadmap for implementation order`
}

## 📁 Documents Included

| Document | Location | Purpose |
|----------|----------|---------|
${docTable}

${
  hasVibe
    ? `## 🤖 AI Handoff

The \`VIBE_PROMPT.md\` file at the root synthesizes all documents above into a single,
actionable instruction. It includes:

- Project identity and goals
- Full tech stack and architecture overview
- Data models and API contracts
- Implementation roadmap with phases
- Coding standards and conventions
- Bootstrap commands to start building

**This is the only file you need to give to your AI assistant.**`
    : ""
}

---

*Generated with [APEX-CYBERNETIC](https://github.com/atticawe/prdbot) — AI-Powered Document Suite*
`;
}
